using System;
using System.IO;
using System.Text;

namespace Hanagumori.UnityPmx.Tests
{
    internal static class PmxStaticImportFixtureBuilder
    {
        public static byte[] Build(string texturePath = "texture.png")
        {
            using (var stream = new MemoryStream())
            using (var writer = new BinaryWriter(stream, Encoding.UTF8, true))
            {
                WriteHeader(writer);
                WriteText(writer, "Static Fixture");
                WriteText(writer, "Static Fixture");
                WriteText(writer, "Generated by UnityPMXEditor tests");
                WriteText(writer, "Generated by UnityPMXEditor tests");

                writer.Write(4);
                WriteVertex(writer, 0, 0, 0, 0, 0);
                WriteVertex(writer, 1, 0, 0, 1, 0);
                WriteVertex(writer, 0, 1, 0, 0, 1);
                WriteVertex(writer, 1, 1, 0, 1, 1);

                writer.Write(6);
                writer.Write((byte)0);
                writer.Write((byte)1);
                writer.Write((byte)2);
                writer.Write((byte)1);
                writer.Write((byte)3);
                writer.Write((byte)2);

                writer.Write(1);
                WriteText(writer, texturePath);

                writer.Write(2);
                WriteMaterial(writer, 0, 3);
                WriteMaterial(writer, -1, 3);

                WriteSingleBone(writer);
                writer.Write(0); // Morph count
                writer.Write(0); // DisplayFrame count
                writer.Write(0); // RigidBody count
                writer.Write(0); // Joint count; PMX 2.0 ends here
                writer.Flush();
                return stream.ToArray();
            }
        }

        public static byte[] BuildLargeVertexFixture(int vertexCount)
        {
            if (vertexCount <= 65535) throw new ArgumentOutOfRangeException(nameof(vertexCount));
            using (var stream = new MemoryStream())
            using (var writer = new BinaryWriter(stream, Encoding.UTF8, true))
            {
                WriteHeader(writer);
                WriteText(writer, "Large Fixture");
                WriteText(writer, "Large Fixture");
                WriteText(writer, string.Empty);
                WriteText(writer, string.Empty);
                writer.Write(vertexCount);
                for (int i = 0; i < vertexCount; i++) WriteVertex(writer, 0, 0, 0, 0, 0);
                writer.Write(0); // Surface index count
                writer.Write(0); // Texture count
                writer.Write(1); // Material count
                WriteMaterial(writer, -1, 0);
                WriteSingleBone(writer);
                writer.Write(0);
                writer.Write(0);
                writer.Write(0);
                writer.Write(0);
                writer.Flush();
                return stream.ToArray();
            }
        }

        public static byte[] BuildSkinnedFixture(bool cyclicHierarchy = false)
        {
            using (var stream = new MemoryStream())
            using (var writer = new BinaryWriter(stream, Encoding.UTF8, true))
            {
                WriteHeader(writer);
                WriteText(writer, "Skinned Fixture");
                WriteText(writer, "Skinned Fixture");
                WriteText(writer, "Late parent and BDEF fixture");
                WriteText(writer, "Late parent and BDEF fixture");

                writer.Write(6);
                WriteBdef1Vertex(writer, -0.5f, -0.5f, 1);
                WriteBdef1Vertex(writer, 0.5f, -0.5f, 0);
                WriteBdef2Vertex(writer, -0.5f, 0.5f, 1, 0, 0.75f);
                WriteBdef4Vertex(writer, 0.5f, -0.5f,
                    new[] { 1, 0, -1, -1 }, new[] { 0f, 2f, 0f, 0f });
                WriteBdef4Vertex(writer, 0.5f, 0.5f,
                    new[] { 1, 0, -1, -1 }, new[] { 1.5f, 0.5f, 0f, 0f });
                WriteBdef1Vertex(writer, -0.5f, 0.5f, -1);

                writer.Write(6);
                foreach (byte index in new byte[] { 0, 1, 2, 3, 4, 5 }) writer.Write(index);
                writer.Write(0); // Texture count
                writer.Write(2);
                WriteMaterial(writer, -1, 3);
                WriteMaterial(writer, -1, 3);

                writer.Write(2);
                WriteBone(writer, "child", 0.5f, 0, 0, cyclicHierarchy ? 0 : 1);
                WriteBone(writer, "root", 0, 0, 0, -1);
                writer.Write(0);
                writer.Write(0);
                writer.Write(0);
                writer.Write(0);
                writer.Flush();
                return stream.ToArray();
            }
        }

        public static byte[] BuildAdvancedDeformFixture()
        {
            using (var stream = new MemoryStream())
            using (var writer = new BinaryWriter(stream, Encoding.UTF8, true))
            {
                WriteHeader(writer, 2.1f);
                WriteText(writer, "Advanced Fixture");
                WriteText(writer, "Advanced Fixture");
                WriteText(writer, "SDEF QDEF fixture");
                WriteText(writer, "SDEF QDEF fixture");
                writer.Write(2);
                WriteAdvancedVertex(writer, PmxVertexWeightType.Sdef);
                WriteAdvancedVertex(writer, PmxVertexWeightType.Qdef);
                writer.Write(0);
                writer.Write(0);
                writer.Write(1);
                WriteMaterial(writer, -1, 0);
                writer.Write(2);
                WriteBone(writer, "root", 0, 0, 0, -1);
                WriteBone(writer, "child", 0.5f, 0, 0, 0);
                writer.Write(0);
                writer.Write(0);
                writer.Write(0);
                writer.Write(0);
                writer.Write(0); // PMX 2.1 SoftBody count
                writer.Flush();
                return stream.ToArray();
            }
        }

        public static byte[] BuildNoBoneFixture()
        {
            using (var stream = new MemoryStream())
            using (var writer = new BinaryWriter(stream, Encoding.UTF8, true))
            {
                WriteHeader(writer);
                WriteText(writer, "No Bone Fixture");
                WriteText(writer, "No Bone Fixture");
                WriteText(writer, string.Empty);
                WriteText(writer, string.Empty);
                writer.Write(1);
                WriteBdef1Vertex(writer, 0, 0, -1);
                writer.Write(0);
                writer.Write(0);
                writer.Write(1);
                WriteMaterial(writer, -1, 0);
                writer.Write(0); // Bone count
                writer.Write(0);
                writer.Write(0);
                writer.Write(0);
                writer.Write(0);
                writer.Flush();
                return stream.ToArray();
            }
        }

        public static byte[] BuildMorphMetadataFixture(bool invalidVertexMorphIndex = false)
        {
            using (var stream = new MemoryStream())
            using (var writer = new BinaryWriter(stream, Encoding.UTF8, true))
            {
                WriteHeader(writer, 2.1f);
                WriteText(writer, "メタデータモデル");
                WriteText(writer, "Metadata Model");
                WriteText(writer, "Original model comment");
                WriteText(writer, "Original English comment");
                writer.Write(4);
                WriteBdef1Vertex(writer, -0.5f, -0.5f, 0);
                WriteBdef1Vertex(writer, 0.5f, -0.5f, 0);
                WriteBdef1Vertex(writer, 0.5f, 0.5f, 1);
                WriteBdef1Vertex(writer, -0.5f, 0.5f, 1);
                writer.Write(3);
                writer.Write((byte)0);
                writer.Write((byte)1);
                writer.Write((byte)2);
                writer.Write(0); // Texture count
                writer.Write(1);
                WriteMetadataMaterial(writer);
                WriteMetadataBones(writer);
                WriteMetadataMorphs(writer, invalidVertexMorphIndex);
                WriteMetadataDisplayFrame(writer);
                WriteMetadataRigidBody(writer);
                WriteMetadataJoint(writer);
                WriteMetadataSoftBody(writer);
                writer.Flush();
                return stream.ToArray();
            }
        }

        public static byte[] BuildPhysicsFixture()
        {
            using (var stream = new MemoryStream())
            using (var writer = new BinaryWriter(stream, Encoding.UTF8, true))
            {
                WriteHeader(writer, 2.1f);
                WriteText(writer, "Physics Fixture");
                WriteText(writer, "Physics Fixture");
                WriteText(writer, "Generated Stage 6 physics fixture");
                WriteText(writer, "Generated Stage 6 physics fixture");

                writer.Write(3);
                WriteBdef1Vertex(writer, -0.5f, 0f, 0);
                WriteBdef1Vertex(writer, 0.5f, 0f, 1);
                WriteBdef1Vertex(writer, 0f, 1f, 2);
                writer.Write(3);
                writer.Write((byte)0);
                writer.Write((byte)1);
                writer.Write((byte)2);
                writer.Write(0); // Texture count
                writer.Write(1);
                WriteMaterial(writer, -1, 3);

                writer.Write(3);
                WriteBone(writer, "follow bone", -2f, 3f, 0f, -1);
                WriteBone(writer, "dynamic bone", 0f, 3f, 0f, -1);
                WriteBone(writer, "physics bone", 2f, 3f, 0f, -1);
                writer.Write(0); // Morph count
                writer.Write(0); // DisplayFrame count

                writer.Write(3);
                WritePhysicsRigidBody(writer, "sphere follow", 0, 0, 0x0002, 0,
                    0.5f, 0.5f, 0.5f, -2f, 3f, 0f, 0);
                WritePhysicsRigidBody(writer, "box dynamic", 1, 1, 0x0000, 1,
                    0.5f, 0.5f, 0.5f, 0f, 3f, 0f, 1);
                WritePhysicsRigidBody(writer, "capsule physics bone", 2, 2, 0x0000, 2,
                    0.35f, 0.8f, 0.35f, 2f, 3f, 0f, 2);

                writer.Write(1);
                WriteText(writer, "spring joint");
                WriteText(writer, "spring joint");
                writer.Write((byte)0); // Spring 6DOF
                writer.Write((sbyte)1);
                writer.Write((sbyte)2);
                WriteVector3(writer, 1f, 3f, 0f);
                WriteVector3(writer, 0f, 0f, 0f);
                WriteVector3(writer, -2f, -0.2f, -0.2f);
                WriteVector3(writer, 2f, 0.2f, 0.2f);
                WriteVector3(writer, -0.2f, -0.2f, -0.2f);
                WriteVector3(writer, 0.2f, 0.2f, 0.2f);
                WriteVector3(writer, 20f, 20f, 20f);
                WriteVector3(writer, 5f, 5f, 5f);

                WriteMetadataSoftBody(writer);
                writer.Flush();
                return stream.ToArray();
            }
        }

        private static void WriteHeader(BinaryWriter writer, float version = 2.0f)
        {
            writer.Write(new byte[] { 0x50, 0x4D, 0x58, 0x20 });
            writer.Write(version);
            writer.Write((byte)8);
            writer.Write((byte)1); // UTF-8
            writer.Write((byte)0); // Additional UV count
            for (int i = 0; i < 6; i++) writer.Write((byte)1);
        }

        private static void WriteVertex(BinaryWriter writer, float x, float y, float z, float u, float v)
        {
            WriteVector3(writer, x, y, z);
            WriteVector3(writer, 0, 0, 1);
            writer.Write(u);
            writer.Write(v);
            writer.Write((byte)0); // BDEF1
            writer.Write((sbyte)0);
            writer.Write(1f);
        }

        private static void WriteBdef1Vertex(BinaryWriter writer, float x, float y, int bone)
        {
            WriteVertexPrefix(writer, x, y);
            writer.Write((byte)PmxVertexWeightType.Bdef1);
            writer.Write(unchecked((sbyte)bone));
            writer.Write(1f);
        }

        private static void WriteBdef2Vertex(BinaryWriter writer, float x, float y,
            int bone0, int bone1, float weight0)
        {
            WriteVertexPrefix(writer, x, y);
            writer.Write((byte)PmxVertexWeightType.Bdef2);
            writer.Write(unchecked((sbyte)bone0));
            writer.Write(unchecked((sbyte)bone1));
            writer.Write(weight0);
            writer.Write(1f);
        }

        private static void WriteBdef4Vertex(BinaryWriter writer, float x, float y,
            int[] bones, float[] weights)
        {
            WriteVertexPrefix(writer, x, y);
            writer.Write((byte)PmxVertexWeightType.Bdef4);
            for (int i = 0; i < 4; i++) writer.Write(unchecked((sbyte)bones[i]));
            for (int i = 0; i < 4; i++) writer.Write(weights[i]);
            writer.Write(1f);
        }

        private static void WriteAdvancedVertex(BinaryWriter writer, PmxVertexWeightType type)
        {
            WriteVertexPrefix(writer, 0, 0);
            writer.Write((byte)type);
            if (type == PmxVertexWeightType.Sdef)
            {
                writer.Write((sbyte)0);
                writer.Write((sbyte)1);
                writer.Write(0.5f);
                WriteVector3(writer, 1, 2, 3);
                WriteVector3(writer, 4, 5, 6);
                WriteVector3(writer, 7, 8, 9);
            }
            else
            {
                writer.Write((sbyte)0);
                writer.Write((sbyte)1);
                writer.Write((sbyte)-1);
                writer.Write((sbyte)-1);
                writer.Write(0.5f);
                writer.Write(0.5f);
                writer.Write(0f);
                writer.Write(0f);
            }
            writer.Write(1f);
        }

        private static void WriteVertexPrefix(BinaryWriter writer, float x, float y)
        {
            WriteVector3(writer, x, y, 0);
            WriteVector3(writer, 0, 0, 1);
            writer.Write(x + 0.5f);
            writer.Write(y + 0.5f);
        }

        private static void WriteMaterial(BinaryWriter writer, int textureIndex, int surfaceIndexCount)
        {
            WriteText(writer, "Duplicate Display Name");
            WriteText(writer, "Duplicate Display Name");
            WriteVector4(writer, 1, 1, 1, 1);
            WriteVector3(writer, 0.2f, 0.2f, 0.2f);
            writer.Write(10f);
            WriteVector3(writer, 0.1f, 0.1f, 0.1f);
            writer.Write((byte)0);
            WriteVector4(writer, 0, 0, 0, 1);
            writer.Write(1f);
            writer.Write(unchecked((sbyte)textureIndex));
            writer.Write((sbyte)-1);
            writer.Write((byte)0);
            writer.Write((byte)1);
            writer.Write((byte)0);
            WriteText(writer, "Stage 2 approximation fixture");
            writer.Write(surfaceIndexCount);
        }

        private static void WriteSingleBone(BinaryWriter writer)
        {
            writer.Write(1);
            WriteText(writer, "root");
            WriteText(writer, "root");
            WriteVector3(writer, 0, 0, 0);
            writer.Write((sbyte)-1);
            writer.Write(0);
            writer.Write((ushort)0);
            WriteVector3(writer, 0, 1, 0);
        }

        private static void WriteBone(BinaryWriter writer, string name,
            float x, float y, float z, int parent)
        {
            WriteText(writer, name);
            WriteText(writer, name);
            WriteVector3(writer, x, y, z);
            writer.Write(unchecked((sbyte)parent));
            writer.Write(0);
            writer.Write((ushort)0);
            WriteVector3(writer, 0, 1, 0);
        }

        private static void WriteMetadataMaterial(BinaryWriter writer)
        {
            WriteText(writer, "材質メタ");
            WriteText(writer, "Material Metadata");
            WriteVector4(writer, 0.8f, 0.7f, 0.6f, 0.9f);
            WriteVector3(writer, 0.3f, 0.4f, 0.5f);
            writer.Write(32f);
            WriteVector3(writer, 0.1f, 0.2f, 0.3f);
            writer.Write((byte)0xA5);
            WriteVector4(writer, 0.1f, 0.1f, 0.1f, 1f);
            writer.Write(1.5f);
            writer.Write((sbyte)-1);
            writer.Write((sbyte)-1);
            writer.Write((byte)2);
            writer.Write((byte)1);
            writer.Write((byte)3);
            WriteText(writer, "material semantic memo");
            writer.Write(3);
        }

        private static void WriteMetadataBones(BinaryWriter writer)
        {
            writer.Write(4);
            WriteText(writer, "IK root");
            WriteText(writer, "IK root");
            WriteVector3(writer, 1, 1, 0);
            writer.Write((sbyte)-1);
            writer.Write(7);
            writer.Write((ushort)0x2C21); // indexed tail, IK, fixed/local axes, external parent
            writer.Write((sbyte)1);
            WriteVector3(writer, 1, 0, 0);
            WriteVector3(writer, 1, 0, 0);
            WriteVector3(writer, 0, 0, 1);
            writer.Write(42);
            writer.Write((sbyte)3);
            writer.Write(4);
            writer.Write(0.5f);
            writer.Write(2);
            writer.Write((sbyte)2);
            writer.Write((byte)1);
            WriteVector3(writer, -3.14f, -3.14f, -3.14f);
            WriteVector3(writer, 3.14f, 3.14f, 3.14f);
            writer.Write((sbyte)1);
            writer.Write((byte)0);

            WriteBone(writer, "grant source", 0, 0, 0, -1);
            WriteGrantBone(writer);
            WriteBone(writer, "effector", 1, 0, 0, 2);
        }

        private static void WriteMetadataMorphs(BinaryWriter writer, bool invalidVertexMorphIndex)
        {
            writer.Write(9);
            WriteMorphHeader(writer, "重複名", "Duplicate Name", PmxMorphType.Vertex, 2);
            writer.Write(invalidVertexMorphIndex ? (byte)255 : (byte)1);
            WriteVector3(writer, 1, 0, 0);
            writer.Write((byte)3);
            WriteVector3(writer, 0, 1, 0);

            WriteMorphHeader(writer, "重複名", "Duplicate Name", PmxMorphType.Vertex, 0);

            WriteMorphHeader(writer, "重複名", "Duplicate Name", PmxMorphType.Vertex, 2);
            writer.Write((byte)2);
            WriteVector3(writer, 0.25f, 0, 0);
            writer.Write((byte)2);
            WriteVector3(writer, 0.75f, 0, 0);

            WriteMorphHeader(writer, "group", "group", PmxMorphType.Group, 1);
            writer.Write((sbyte)0);
            writer.Write(0.5f);

            WriteMorphHeader(writer, "bone", "bone", PmxMorphType.Bone, 1);
            writer.Write((sbyte)1);
            WriteVector3(writer, 1, 2, 3);
            writer.Write(0f);
            writer.Write(0f);
            writer.Write(0.258819f);
            writer.Write(0.9659258f);

            WriteMorphHeader(writer, "uv", "uv", PmxMorphType.Uv, 1);
            writer.Write((byte)0);
            WriteVector4(writer, 0.1f, 0.2f, 0.3f, 0.4f);

            WriteMorphHeader(writer, "material", "material", PmxMorphType.Material, 1);
            writer.Write((sbyte)-1);
            writer.Write((byte)1);
            WriteVector4(writer, 1, 1, 1, 1);
            WriteVector3(writer, 1, 1, 1);
            writer.Write(1f);
            WriteVector3(writer, 1, 1, 1);
            WriteVector4(writer, 1, 1, 1, 1);
            writer.Write(1f);
            WriteVector4(writer, 1, 1, 1, 1);
            WriteVector4(writer, 1, 1, 1, 1);
            WriteVector4(writer, 1, 1, 1, 1);

            WriteMorphHeader(writer, "flip", "flip", PmxMorphType.Flip, 1);
            writer.Write((sbyte)0);
            writer.Write(0.75f);

            WriteMorphHeader(writer, "impulse", "impulse", PmxMorphType.Impulse, 1);
            writer.Write((sbyte)0);
            writer.Write((byte)1);
            WriteVector3(writer, 1, 2, 3);
            WriteVector3(writer, 4, 5, 6);
        }

        private static void WriteMorphHeader(BinaryWriter writer, string name, string english,
            PmxMorphType type, int offsetCount)
        {
            WriteText(writer, name);
            WriteText(writer, english);
            writer.Write((byte)1);
            writer.Write((byte)type);
            writer.Write(offsetCount);
        }

        private static void WriteMetadataDisplayFrame(BinaryWriter writer)
        {
            writer.Write(1);
            WriteText(writer, "display");
            WriteText(writer, "display");
            writer.Write((byte)1);
            writer.Write(2);
            writer.Write((byte)0);
            writer.Write((sbyte)0);
            writer.Write((byte)1);
            writer.Write((sbyte)0);
        }

        private static void WriteGrantBone(BinaryWriter writer)
        {
            WriteText(writer, "grant child");
            WriteText(writer, "grant child");
            WriteVector3(writer, 0.5f, 0, 0);
            writer.Write((sbyte)1);
            writer.Write(1);
            writer.Write((ushort)0x0300);
            WriteVector3(writer, 0.5f, 0, 0);
            writer.Write((sbyte)1);
            writer.Write(0.5f);
        }

        private static void WriteMetadataRigidBody(BinaryWriter writer)
        {
            writer.Write(1);
            WriteText(writer, "rigid");
            WriteText(writer, "rigid");
            writer.Write((sbyte)0);
            writer.Write((byte)3);
            writer.Write((ushort)0xFFF0);
            writer.Write((byte)1);
            WriteVector3(writer, 1, 2, 3);
            WriteVector3(writer, 4, 5, 6);
            WriteVector3(writer, 0.1f, 0.2f, 0.3f);
            writer.Write(2f);
            writer.Write(0.1f);
            writer.Write(0.2f);
            writer.Write(0.3f);
            writer.Write(0.4f);
            writer.Write((byte)2);
        }

        private static void WritePhysicsRigidBody(BinaryWriter writer, string name,
            int boneIndex, byte collisionGroup, ushort nonCollisionMask, byte shape,
            float sizeX, float sizeY, float sizeZ, float positionX, float positionY,
            float positionZ, byte physicsMode)
        {
            WriteText(writer, name);
            WriteText(writer, name);
            writer.Write(unchecked((sbyte)boneIndex));
            writer.Write(collisionGroup);
            writer.Write(nonCollisionMask);
            writer.Write(shape);
            WriteVector3(writer, sizeX, sizeY, sizeZ);
            WriteVector3(writer, positionX, positionY, positionZ);
            WriteVector3(writer, 0f, 0f, 0f);
            writer.Write(1f);
            writer.Write(0.05f);
            writer.Write(0.1f);
            writer.Write(0.05f);
            writer.Write(0.5f);
            writer.Write(physicsMode);
        }

        private static void WriteMetadataJoint(BinaryWriter writer)
        {
            writer.Write(1);
            WriteText(writer, "joint");
            WriteText(writer, "joint");
            writer.Write((byte)5);
            writer.Write((sbyte)0);
            writer.Write((sbyte)-1);
            for (int i = 0; i < 8; i++) WriteVector3(writer, i, i + 1, i + 2);
        }

        private static void WriteMetadataSoftBody(BinaryWriter writer)
        {
            writer.Write(1);
            WriteText(writer, "soft");
            WriteText(writer, "soft");
            writer.Write((byte)0);
            writer.Write((sbyte)0);
            writer.Write((byte)2);
            writer.Write((ushort)0xFFFC);
            writer.Write((byte)0x85);
            writer.Write(1);
            writer.Write(2);
            writer.Write(3f);
            writer.Write(0.25f);
            writer.Write(4);
            for (int i = 0; i < 12; i++) writer.Write(i + 0.1f);
            for (int i = 0; i < 6; i++) writer.Write(i + 0.2f);
            writer.Write(1);
            writer.Write(2);
            writer.Write(3);
            writer.Write(4);
            writer.Write(0.5f);
            writer.Write(0.6f);
            writer.Write(0.7f);
            writer.Write(1);
            writer.Write((sbyte)0);
            writer.Write((byte)0);
            writer.Write((byte)1);
            writer.Write(1);
            writer.Write((byte)1);
        }

        private static void WriteText(BinaryWriter writer, string value)
        {
            byte[] bytes = new UTF8Encoding(false, true).GetBytes(value);
            writer.Write(bytes.Length);
            writer.Write(bytes);
        }

        private static void WriteVector3(BinaryWriter writer, float x, float y, float z)
        { writer.Write(x); writer.Write(y); writer.Write(z); }

        private static void WriteVector4(BinaryWriter writer, float x, float y, float z, float w)
        { writer.Write(x); writer.Write(y); writer.Write(z); writer.Write(w); }
    }
}
